version: '3.1'

services:
  db:
    image: mysql/mysql-server:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: 12345678
      MYSQL_DATABASE: chat
      MYSQL_USER: user
    ports:
      - '3306:3306'